# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Gyj1109's Blog
subtitle: 世界那么大 我想去看看
author: Gyj1109
language:
timezone:

# URL
## If your site is put in a subdirectory, set url as 'https://yoursite.com/child' and root as '/child/'
url: 'https://gyj1109.top'
permalink: archives/:year:month:day/:title/
permalink_defaults:

#Custom Setting Start

# Site settings
SEOTitle: Gyj1109's Blog
email: gaoyj1109@gmail.com
description: ""
keyword: ""


# SNS settings
# RSS: false
#weibo_username:               # input your Weibo UUID
zhihu_username:     gyj1109
github_username:    gyj1109
twitter_username:   gyj1109
#facebook_username:
#linkedin_username:

# Build settings

# Disqus settings
#disqus_username:

# Duoshuo settings
# duoshuo_username: kaijun
# Share component is depend on Comment so we can NOT use share only.
# duoshuo_share: true                     # set to false if you want to use Comment without Sharing


# Analytics settings
# Baidu Analytics
#ba_track_id:
# Google Analytics
ga_track_id: 'UA-91573622-1'
ga_domain: gyj1109.top


# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Vidar Team | Reverse | Misc"


# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value


# Friends
friends: [
    {
        title: "cj的小站",
        href: "https://cjovi.icu/"
    },
    {
        title: "Summer's personal blog",
        href: "https://blog.m1dsummer.top/"
    },
    {
        title: "0wl's Blog",
        href: "https://0wl-alt.github.io/"
    },
    {
        title: "云游君的小站",
        href: "https://wr-web.github.io/"
    }
]


#Custom Setting End



# Directory
source_dir: source
public_dir: public
tag_dir: tags
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :year-:month-:day-:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link.enable: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: false
prismjs:
  enable: true
  preprocess: true
  line_number: true
  tab_replace: '    '

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## https://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: huxblog

plugins:
  - hexo
  - hexo-all-minifier
  - hexo-cdn-jsdelivr
  - hexo-generator-archive
  - hexo-generator-category
  - hexo-generator-index-pin-top
  - hexo-generator-index
  - hexo-generator-search
  - hexo-generator-sitemap
  - hexo-generator-tag
  - hexo-renderer-ejs
  - hexo-renderer-markdown-it
  - hexo-renderer-stylus

jsdelivr_cdn:
  # If use_cdn is false, this plugin will not work
  use_cdn: true

  # If deploy_when_generating is true, the assets repository will be pushed to github every time you generate the hexo project using 'hexo g' command. If this flag is set false, the repository will be pushed when deploying. You can manually push the assets repository to github when generating by using 'hexo g cdn' command.
  deploy_when_generating: true

  # cdn_url_prefix is the jsdelivr cdn url of your github repository(the assets repository for static assets rather than the hexo project deployment repository), it should be like: https://cdn.jsdelivr.net/gh/<username for github>/<assets repo name>/
  cdn_url_prefix: 'https://cdn.jsdelivr.net/gh/gyj1109/Blog-Resources/'

  # git_repo_url is the url of your new assets repository on github
  git_repo_url: 'https://github.com/gyj1109/Blog-Resources.git'

  # you can use github token to push your assets repository. If you don't want to use a token, you can use a empty string '' or comment out this line. We do not recommand that you directly write your token in the _config.yml. We suggest that you read the token from the environment variable by setting token with a prefix '$'. e.g. '$GITHUB_TOKEN'. When you want to use token, you must use http(s) link of your repo. More information about github token can be found in https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line.
  token: '$UPLOAD_TOKEN'

  # The path of an asset directory in asset_dirs should be the relative path to your hexo project directory, e.g. assets or source/assets or themes/<theme name>/assets. If you only want to use the cdn for the images in your posts, you can leave asset_dirs as empty
  asset_dirs:
    - icons
    - source/img
    - themes/huxblog/source

markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: true
    linkify: true
    typographer: true
    quotes: '“”‘’'
  plugins:
    - markdown-it-abbr
    - markdown-it-cjk-breaks
    - markdown-it-container
    - markdown-it-footnote
    - markdown-it-ins
    - markdown-it-sub
    - markdown-it-sup

js_concator:
  enable: false
  bundle_path: '/js/bundle.js'
  front: false
  silent: false
html_minifier:
  enable: true
  ignore_error: false
  silent: false
css_minifier:
  enable: true
  silent: false
  exclude:
    - '*.min.css'
js_minifier:
  enable: true
  mangle: true
  silent: false
  exclude:
    - '*.min.js'
image_minifier:
  enable: false
  interlaced: false
  multipass: false
  optimizationLevel: 2
  pngquant: false
  progressive: false
  silent: false

search:
  path: search.xml
  field: post

sitemap:
  path: sitemap.xml
  template: ./sitemap.xml
  rel: true
  tags: false
  categories: false
