# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Gyj1109's Blog
subtitle: 世界那么大 我想去看看
author: Gyj1109
language:
timezone:

# URL
## If your site is put in a subdirectory, set url as 'https://yoursite.com/child' and root as '/child/'
url: https://gyj1109.top
permalink: archives/:year:month:day/:title/
permalink_defaults:

#Custom Setting Start

# Site settings
SEOTitle: Gyj1109's Blog
email: gaoyj1109@gmail.com
description: ""
keyword: ""


# SNS settings
# RSS: false
#weibo_username:               # input your Weibo UUID
zhihu_username:     gyj1109
github_username:    gyj1109
twitter_username:   gyj1109
#facebook_username:
#linkedin_username:

# Build settings
anchorjs: false                          # if you want to customize anchor. check out line:181 of `post.html`


# Disqus settings
#disqus_username:

# Duoshuo settings
# duoshuo_username: kaijun
# Share component is depend on Comment so we can NOT use share only.
# duoshuo_share: true                     # set to false if you want to use Comment without Sharing


# Analytics settings
# Baidu Analytics
#ba_track_id:
# Google Analytics
ga_track_id: 'UA-91573622-1'
ga_domain: gyj1109.top


# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Vidar Team | Reverse | Misc"
sidebar-avatar: img/avatar-gyj1109.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`


# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value


# Friends
friends: [
    {
        title: "cj的小站",
        href: "https://cjovi.icu/"
    },
    {
        title: "Summer's personal blog",
        href: "https://blog.m1dsummer.top/"
    },
    {
        title: "0wl's Blog",
        href: "https://0wl-alt.github.io/"
    },
    {
        title: "云游君的小站",
        href: "https://wr-web.github.io/"
    }
]


#Custom Setting End



# Directory
source_dir: source
public_dir: public
tag_dir: tags
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :year-:month-:day-:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: false
prismjs:
  enable: false
prism_plugin:
  mode: 'preprocess'    # realtime/preprocess
  theme: 'base16-ateliersulphurpool.light'
  line_number: true

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## https://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: huxblog

plugins:
  - hexo
  - hexo-blog-encrypt
  - hexo-filter-flowchart
  - hexo-footnotes
  - hexo-generator-amp
  - hexo-generator-archive
  - hexo-generator-baidu-sitemap
  - hexo-generator-category
  - hexo-generator-index-pin-top
  - hexo-generator-index
  - hexo-generator-search
  - hexo-generator-sitemap
  - hexo-generator-tag
  - hexo-github
  - hexo-neat
  - hexo-prism-plugin
  - hexo-renderer-ejs
  - hexo-renderer-kramed
  - hexo-renderer-marked
  - hexo-renderer-stylus
  - hexo-server

neat_enable: true
neat_html:
  enable: true
  exclude:
neat_css:
  enable: true
  exclude:
    - '*.min.css'
    - '**.min.css'
    - '**/*.min.css'
    - '**\*.min.css'
neat_js:
  enable: true
  mangle: true
  output:
  compress:
  exclude:
    - '*.min.js'
    - '**.min.js'
    - '**/*.min.js'
    - '**\*.min.js'

marked:
  gfm: true
  pedantic: false
  sanitize: false
  tables: true
  breaks: true
  smartLists: true
  smartypants: true

search:
  path: search.xml
  field: post

generator_amp:
  templateDir:  amp
  assetDistDir: amp
  templateFilePath: amp.ejs
  logo:
    path:   nothing.png
    width:  1
    height: 1
  substituteTitleImage:
    path:   nothing.png
    width:  1000
    height: 1000
  html_minifier: true
  warningLog: false
  validateAMP: false

encrypt:
  enable: true
  pwdfile: passwd
